dist: trusty

group: edge
language: bash
addons:
    packages:
    - shellcheck
    - maim
    - slop
    - xclip
    - libnotify-bin
script:
  - bash setup.sh
  - sed -i /userkey=/c\userkey="$key" $HOME/.config/owo/conf.cfg
  - bash script.sh script.sh
sudo: required
